app/main/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField, BooleanField, SubmitField, SelectField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField(u'用户名', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[DataRequired()])
    # remember_me = BooleanField('Keep me logged in')
    submit = SubmitField(u'登录')


class AddServerForm(FlaskForm):
    # server_name = StringField(u'服务器名称', validators=[DataRequired()])
    server_ip = StringField(u'服务器 IP', validators=[DataRequired()])
    server_username = StringField(u'服务器用户名', validators=[DataRequired()])
    server_password = PasswordField(u'服务器密码', validators=[DataRequired()])
    server_port = StringField(u'服务器端口', validators=[DataRequired()], default=22)
    server_env = SelectField(u'所属环境', choices=[('1', 'production'),('2', 'test'), ('3', 'dev')], default=1)
    server_tag = StringField(u'标签', validators=[DataRequired()])
    server_os = SelectField(u'系统类型', choices=[('1', u'Linux'), ('2', u'Windows')], default=1)
    server_type = SelectField(u'服务器类型', choices=[('1', u'物理机'),('2', u'虚拟机')], default=1)
    server_loc = StringField(u'机房机架号')
    submit = SubmitField(u'添加')



class UpdateServerForm(FlaskForm):
    # server_username = StringField(u'服务器用户名', validators=[DataRequired()])
    # server_password = PasswordField(u'服务器密码', validators=[DataRequired()])
    server_ip = StringField(u'服务器 IP', render_kw={'readonly': True})
    server_port = StringField(u'服务器端口', validators=[DataRequired()], default=22)
    server_env = SelectField(u'所属环境', choices=[('1', 'production'),('2', 'test'), ('3', 'dev')], default=1)
    server_tag = StringField(u'标签', validators=[DataRequired()])
    server_type = SelectField(u'服务器类型', choices=[('1', u'物理机'),('2', u'虚拟机')], default=1)
    server_loc = StringField(u'机房机架号')
    submit = SubmitField(u'修改')


class AddInstanceForm(FlaskForm):
    server_ip = StringField(u'服务器 IP', validators=[DataRequired()])
    instance_name = StringField(u'实例名', validators=[DataRequired()])
    instance_username = StringField(u'实例用户名', validators=[DataRequired()])
    instance_password = PasswordField(u'实例密码', validators=[DataRequired()])
    instance_type = SelectField(u'实例类型', choices=[('1', 'MySQL'),('2', 'SQL SERVER')], default=1)
    instance_port = StringField(u'实例端口', validators=[DataRequired()])
    submit = SubmitField(u'添加')


class NewInstanceForm(FlaskForm):
    server_ip = StringField(u'服务器 IP', validators=[DataRequired()])
    instance_name = StringField(u'实例名', validators=[DataRequired()])
    instance_mem = StringField(u'分配内存', validators=[DataRequired()])
    instance_disk = StringField(u'预估空间', validators=[DataRequired()])
    instance_type = SelectField(u'实例类型', choices=[('1', 'MySQL')], default=1)
    instance_port = StringField(u'实例端口', validators=[DataRequired()])
    submit = SubmitField(u'新建')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
import sys
reload(sys)
sys.setdefaultencoding("utf-8")


import ipaddress
import hashlib
from forms import LoginForm, AddServerForm, UpdateServerForm, AddInstanceForm
from flask import (render_template,
				   g,
				   request,
				   abort,
				   session,
				   redirect,
				   url_for,
				   flash)

import MySQLdb as mdb

import functions as func
from config import config
from . import main


@main.before_request
def before_request():
	g.db = mdb.connect(**config.db_config)


@main.route('/', methods=['GET', 'POST'])
@main.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		form_password = form.password.data
		username = form.username.data
		# remember_me = form.remember_me.data
		salt = func.get_salt(username)
		password = hashlib.md5(hashlib.md5(form_password + salt).hexdigest()).hexdigest()
		if not func.verify_user(username):
			flash('Invalid username.')
		elif not func.verify_password(username, password):
			flash('Invalid password.')
		else:
			session['logged_in'] = True
			session['username'] = username
			return redirect(url_for('main.portal'))
	return render_template('login.html', form=form)


@main.route('/logout')
def logout():
	# remove the username from the session if it's there
	session.pop('username', None)
	session.pop('logged_in', None)
	flash('You have been logged out.')
	return redirect(url_for('main.login'))


@main.route('/portal', methods=['GET', 'POST'])
def portal():
	return render_template('main.html')


@main.route('/server/<int:server_env>', methods=['GET', 'POST'])
def server(server_env):
	page = request.args.get('page', 1, type=int)
	query = """ SELECT id,server_hostname, inet_ntoa(server_ip),server_env,server_tag,server_os,
  				server_version,server_cpu,server_mem,server_disk,server_type,server_loc 
  				FROM infra_server WHERE server_env = '%s' AND is_delete=0 LIMIT %s OFFSET %s """ % (
		server_env, config.POSTS_PER_PAGE, config.POSTS_PER_PAGE * (page - 1))
	c = g.db.cursor()
	c.execute(query)
	servers = [dict(id=row[0], server_hostname=row[1], server_ip=row[2], server_env=row[3], server_tag=row[4],
				server_os=row[5], server_version=row[6], server_cpu=row[7], server_mem=row[8], server_disk=row[9],
				server_type=row[10], server_loc=row[11]) for row in c.fetchall()]
	pagination = func.paginate('infra_server', 'server_env = ' + str(server_env) + ' AND is_delete = 0', page)

	return render_template('server.html', endpoint='main.server', server_env=server_env, servers=servers,pagination=pagination)


@main.route('/server/add', methods=['GET', 'POST'])
def add_server():
	form = AddServerForm()
	if form.validate_on_submit():
		server_ip = form.server_ip.data
		server_username = form.server_username.data
		server_password = form.server_password.data
		server_port = form.server_port.data
		server_env = form.server_env.data
		server_tag = form.server_tag.data
		server_os = form.server_os.data
		server_type = form.server_type.data
		server_loc = form.server_loc.data
		if func.is_connect_server(server_ip, server_username, server_port, server_password):
			server_info = func.collect_info(server_ip, server_username, server_port, server_password)
			query = """INSERT INTO infra_server(server_hostname,server_ip,server_username,server_password, server_port, server_env,server_tag,
						server_os,server_version,server_cpu, server_mem,server_disk,server_type,server_loc)
					  VALUES('%s','%s','%s','%s',%s,%s,'%s','%s','%s', %s, %s, %s,%s,'%s')		  
			""" % (
				server_info['hostname'], int(ipaddress.ip_address(server_ip)), server_username, server_password, server_port, server_env, server_tag, server_os,
				server_info['release'],
				int(server_info['cpuinfo']), int(server_info['meminfo']), int(server_info['diskinfo'])/1024/1024, server_type, server_loc)
			c = g.db.cursor()
			c.execute(query)
			g.db.commit()
			return redirect(url_for('main.server', server_env=server_env))
		else:
			flash(u'connect failed, invalid username or password!')
	return render_template('add_server.html', form=form)


@main.route('/server/<int:server_id>', methods=['GET', 'POST'])
def get_serverinfo(server_id):
	query = """SELECT id,server_hostname, inet_ntoa(server_ip),server_env,server_tag,server_os,
  				server_version,server_cpu,server_mem,server_disk,server_type,server_loc 
  				FROM infra_server WHERE id=%s """ %(server_id)
	c = g.db.cursor()
	c.execute(query)
	servers = [dict(id=row[0], server_hostname=row[1], server_ip=row[2], server_env=row[3], server_tag=row[4],
					server_os=row[5], server_version=row[6], server_cpu=row[7], server_mem=row[8], server_disk=row[9],
					server_type=row[10], server_loc=row[11]) for row in c.fetchall()]
	return render_template('server.html', servers=servers)

@main.route('/server/<int:server_id>/edit', methods=['GET', 'POST'])
def update_server(server_id):
	if not session.get('logged_in'):
		abort(401)
	form = UpdateServerForm()
	if form.validate_on_submit():
		server_port = form.server_port.data
		server_env = form.server_env.data
		server_tag = form.server_tag.data
		server_type = form.server_type.data
		server_loc = form.server_loc.data
		update_server = """ UPDATE infra_server 
 							SET server_port=%s, server_env=%s, server_tag='%s', server_type=%s,server_loc='%s'
 							WHERE id= %s """ % (server_port, server_env, server_tag, server_type, server_loc, server_id)
		c = g.db.cursor()
		c.execute(update_server)
		g.db.commit()
		flash('server has been updated successfully.')
		return redirect(url_for('main.server', server_env=server_env))
	form.server_ip.data = func.get_serverip(server_id)
	return render_template('update_server.html', form=form)


@main.route('/server/<int:server_env>/<int:server_id>/delete', methods=['GET', 'POST'])
def delete_server(server_env, server_id):
	if not session.get('logged_in'):
		abort(401)
	delete_server = "UPDATE infra_server SET is_delete = 1 WHERE id = %s" % server_id
	c = g.db.cursor()
	c.execute(delete_server)
	g.db.commit()

	flash('server has been deleted successfully.')
	return redirect(url_for('main.server', server_env=server_env))


@main.route('/instance/<int:instance_type>', methods=['GET', 'POST'])
def instance(instance_type):
	page = request.args.get('page', 1, type=int)
	query = """SELECT id, inet_ntoa(server_ip), instance_name, instance_port, instance_type FROM infra_instance WHERE instance_type=%s AND is_delete = 0 LIMIT %s OFFSET %s """ \
			% (instance_type, config.POSTS_PER_PAGE, config.POSTS_PER_PAGE * (page - 1))
	c = g.db.cursor()
	c.execute(query)
	instances = [dict(id=row[0], server_ip=row[1], instance_name=row[2], instance_port=row[3], instance_type=row[4]) for row in c.fetchall()]
	pagination = func.paginate('infra_instance', 'instance_type = ' + str(instance_type) + ' AND is_delete = 0', page)
	return render_template('instance.html', endpoint='main.instance', instance_type=instance_type, instances=instances, pagination=pagination)


@main.route('/instance/<int:instance_type>/add', methods=['GET', 'POST'])
def add_instance(instance_type):
	if not session.get('logged_in'):
		abort(401)
	form = AddInstanceForm()
	if form.validate_on_submit():
		server_ip = form.server_ip.data
		instance_name = form.instance_name.data
		instance_username = form.instance_username.data
		instance_password = form.instance_password.data
		instance_port = form.instance_port.data
		if func.is_connect_mysql(server_ip, instance_username, instance_password, instance_port) :
			add_instance = """INSERT INTO infra_instance(server_ip, instance_name, instance_type, instance_username, instance_password, instance_port)
						VALUES(%s,'%s', %s, '%s','%s', %s) """ %(int(ipaddress.ip_address(server_ip)), instance_name, instance_type, instance_username, instance_password, instance_port)
			c = g.db.cursor()
			c.execute(add_instance)
			g.db.commit()
			return redirect(url_for('main.instance', instance_type=instance_type))
		else:
			flash(u"connect failed, invalid username or password!")
	return render_template('add_instance.html', form=form)


@main.route('/instance/<int:instance_type>/<int:instance_id>/delete', methods=['GET', 'POST'])
def delete_instance(instance_type, instance_id):
	if not session.get('logged_in'):
		abort(401)
	delete_instance = """UPDATE infra_instance SET is_delete = 1 WHERE id = %s""" %(instance_id)
	c = g.db.cursor()
	c.execute(delete_instance)
	g.db.commit()
	return redirect(url_for('main.instance', instance_type=instance_type))

app/templates/_comment.html
<ul class="comments">
    {% for comment in comments %}
        <li class="comment">
            <div class="post-comment">
                <div class="comment-author">
                    {{ comment.reply_username }}
                    {% if  comment.comment_username %}
                        <span class="comment-date"> Reply </span>
                        {{ comment.comment_username }}
                    {% endif %}
                    <span class="comment-date">{{ comment.create_at }}</span>
                </div>
                <div class="comment-content">
                    {{ comment.content }}
                </div>

                <div>
                    <a href="#" class="reply" commentid={{ comment.comment_id }} data-toggle="modal" data-target="#commentModel">Reply</a>
                    {% if user == session.username  %}
                        <a class="reply" href="{{ url_for('main.delete_comment', username=user, post_id=postid, comment_id=comment.comment_id) }}">Delete</a>
                    {% endif %}
                    <!-- 模态框（Modal） -->
                    <div class="modal fade" id="commentModel" aria-hidden="true" tabindex="-1" role="dialog"
                         aria-labelledby="myModalLabel">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="myModalLabel">Reply</h4>
                                </div>
                                <div class="modal-body">
                                    {{ wtf.quick_form(form) }}
                                </div>
{#                                <div class="modal-footer">#}
{#                                    <a class="btn btn-default"#}
{#                                       href="{{ url_for('main.reply', comment_id = comment.comment_id) }}"> Reply</a>#}
{#                                </div>#}
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal -->
                    </div>
                </div>
            </div>
        </li>
    {% endfor %}
</ul>

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='' ) %}
<ul class="pagination posts">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for page in range(1, pagination.pagecount + 1) %}
        {% if page %}
            {% if page == pagination.page %}
                <li class="active">
                    <a href="{{ url_for(endpoint,page=page, **kwargs)}}{{ fragment }}">{{ page }}</a>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for(endpoint,page=page, **kwargs)}}{{ fragment }}" class="active">{{ page }}</a>
                </li>
            {% endif %}
        {% else %}
            <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/add_instance.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login &middot; SA 系统 {% endblock %}


{% block page_content %}
    {% if  session.logged_in %}


        <div class="page-header">
            <h1>Add Instance</h1>
        </div>

        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    {% endif %}

{% endblock %}

app/templates/add_server.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login &middot; SA 系统 {% endblock %}


{% block page_content %}
    {% if  session.logged_in %}


        <div class="page-header">
            <h1>Add Server</h1>
        </div>

        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    {% endif %}

{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}SA 系统{% endblock %}

{% block head %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='we3.png') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='we3.png') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">SA 系统</a>

            </div>

            <div class="navbar-collapse collapse">
                 <ul class="nav navbar-nav">
                     {% if session.logged_in %}
                         <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 服务器管理 <span
                                    class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('main.server', server_env=1) }}">production</a></li>
                                <li><a href="{{ url_for('main.server', server_env=2) }}">test</a></li>
                                <li><a href="{{ url_for('main.server', server_env=3) }}">dev</a></li>
                            </ul>
                        </li>
                         <li class="dropdown">
                            <a href="{{ url_for('main.instance',instance_type=1) }}" class="dropdown-toggle"> MySQL 管理 <span
                                    class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url_for('main.add_instance', instance_type=1) }}">添加 MySQL</a></li>
                                <li><a href="#">新建 MySQL</a></li>
                            </ul>
                        </li>
                         <li><a href="#"> 备份管理</a></li>
                         <li><a href="http://10.1.3.126:10010/graph/dashboard/db/cross-server-graphs?refresh=1m&orgId=1"> 监控系统</a></li>
                         <li><a href="http://10.1.3.126:10010/graph/dashboard/db/_pmm-query-analytics?orgId=1&var-host=baiy-3306"> MySQL 慢查询</a></li>
                    {% endif %}
                 </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not session.logged_in %}
                        <li><a href="{{ url_for('main.login') }}">登 录</a></li>
                    {% else %}
                        <li>
                            <a href="#">{{ session.username }}</a>
                        </li>
                        <li><a href="{{ url_for('main.logout') }}">退 出</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container" style="
        padding-top: 70px;
        padding-bottom: 20px;
    ">

        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}{% endblock %}
    </div>

{% endblock %}

app/templates/instance.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %} server &middot; SA 系统 {% endblock %}

{% block page_content %}
    <div class="container">
        {% for instance in instances %}
            <div class="col-sm-6 col-md-4">
                <h3>{{ instance.instance_name }} </h3>
                <span class="badge">{{ instance.server_ip }}</span>
                {% if  instance.instance_type == 1 %}
                    <span class="label label-success">MySQL</span>
                {% elif instance.instance_type == 2 %}
                    <span class="label label-info">SQL SERVER</span>
                {% endif %}
                <span class="label label-warning">{{ instance.instance_port }} </span>
                <div class="server">
                    <button class="btn btn-danger" data-toggle="modal" data-target="#confirm-delete"
                       data-href="{{ url_for("main.delete_instance",instance_type=instance.instance_type, instance_id=instance.id) }}">Delete</button>
                </div>
                <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                请确认
                            </div>
                            <div class="modal-body">
                                确认删除 {{ instance.instance_name }} 该记录吗？
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-danger btn-ok">删除</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <span><em>Unbelievable. No entries here so far</em></span>
        {% endfor %}
    </div>

    <div class="pagination">
        {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, endpoint, instance_type=instance_type) }}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        });
    </script>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login &middot; SA 系统 {% endblock %}


{% block page_content %}
{#{% if not session.logged_in %}#}


    <div class="page-header">
        <h1>Login</h1>
        <small>Page</small>
    </div>

    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    {#    <br>#}
    {#    <p>Forgot your password? <a href="{{ url_for('auth.password_reset_request') }}">Click here to reset it</a>.</p>#}
    {#    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>#}
    </div>



{#{% endif %}#}

{% endblock %}

app/templates/main.html
{% extends "base.html" %}

{% block title %} HOME &middot; SA  {% endblock %}


{% block page_content %}

    <div class="page-header">
        <h1>hello world!</h1>
        <small>Page</small>
    </div>

{% endblock %}

app/templates/server.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %} server &middot; SA 系统 {% endblock %}

{% block page_content %}
    <div class="container">
        {% for server in servers %}
            <div class="col-sm-6 col-md-4">
                <h3>{{ server.server_ip }} </h3>
                <span class="badge">{{ server.server_hostname }}</span>
                {% if  server.server_env == 1 %}
                    <span class="label label-danger">production</span>
                {% elif server.server_env == 2 %}
                    <span class="label label-info">test</span>
                {% elif server.server_env == 3 %}
                    <span class="label label-warning">dev</span>
                {% endif %}
                {% if  server.server_os  == 1 %}
                    <span class="label label-primary">Linux</span>
                {% elif server.server_os == 2 %}
                    <span class="label label-primary">Windows</span>
                {% elif server.server_os == 3 %}
                    <span class="label label-primary">Ali</span>
                {% endif %}
                <span class="label label-danger">{{ server.server_version }}</span>
                {% if  server.server_type == 1 %}
                    <span class="label label-success">物理机</span>
                {% else %}
                    <span class="label label-default">虚拟机</span>
                {% endif %}
                <span class="label label-warning">内存:{{ server.server_mem }} G </span>
                <span class="label label-success">CPU:{{ server.server_cpu }} 核 </span>
                <span class="label label-info">磁盘:{{ server.server_disk }} G</span>
                <div class="server">
                    <a class="btn btn-default"
                       href="{{ url_for("main.update_server",server_id=server.id) }}">Edit</a>
                    <button class="btn btn-danger" data-toggle="modal" data-target="#confirm-delete"
                       data-href="{{ url_for("main.delete_server",server_env=server.server_env, server_id=server.id) }}">Delete</button>
                </div>
                <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                请确认
                            </div>
                            <div class="modal-body">
                                确认删除 {{ server.server_ip }} 该记录吗？
                            </div>
                            <div class="modal-footer">
                                <a class="btn btn-danger btn-ok">删除</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            <span><em>Unbelievable. No entries here so far</em></span>
        {% endfor %}
    </div>

    <div class="pagination">
        {% if pagination %}
            <div class="pagination">
                {{ macros.pagination_widget(pagination, endpoint, server_env=server_env) }}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        });
    </script>
{% endblock %}

app/templates/update_server.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Login &middot; SA 系统 {% endblock %}


{% block page_content %}
    {% if  session.logged_in %}


        <div class="page-header">
            <h1>Update Server</h1>
        </div>

        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    {% endif %}

{% endblock %}